name: monthly_calendar_example
description: A short demo of the monthly_calendar package.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  monthly_calendar:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=3.0.0 < 7.0.0'

flutter:
  uses-material-design: true
